version: "3.7"

services:
  back-end:
    build: ./back_end
    # for testing : to reach node connector within docker bridge network
    network_mode: bridge
    environment:
      - PORT=8888
      - NODE_CONNECTOR_URL=172.17.0.2:8080
  front-end:
    build: ./front_end
    # for testing : to reach node connector within docker bridge network
    network_mode: bridge
    ports:
      - "80:80"
    depends_on:
      - back-end

networks:
  bridge:
    driver: bridge
